// Css
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
// module
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ProviderContext from '@/components/provider/ProviderContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Genshin Shop',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProviderContext>{children}</ProviderContext>
            </body>
        </html>
    );
}
